/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-10-26 21:43:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class genearateReports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.html", Long.valueOf(1666744508529L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head><title>\n");
      out.write("	Generate Reports\n");
      out.write("</title><link href=\"Styles/HMSMENU.css\" rel=\"stylesheet\" />\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\n");
      out.write("     <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /><link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" />\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        \n");
      out.write("        .link\n");
      out.write("        {\n");
      out.write("            text-decoration:none;\n");
      out.write("            font-family:Calibri;\n");
      out.write("\n");
      out.write("        }\n");
      out.write("    \n");
      out.write("        form {\n");
      out.write("    border: 3px solid #f1f1f1;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("input[type=text], input[type=password] {\n");
      out.write("    width: 100%;\n");
      out.write("    padding: 12px 20px;\n");
      out.write("    margin: 8px 0;\n");
      out.write("    display: inline-block;\n");
      out.write("    border: 1px solid #ccc;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/*.button {\n");
      out.write("    background-color: #4CAF50;\n");
      out.write("    color: white;\n");
      out.write("    padding: 14px 20px;\n");
      out.write("    margin: 8px 0;\n");
      out.write("    border: none;\n");
      out.write("    cursor: pointer;\n");
      out.write("    width: 100%;\n");
      out.write("}*/\n");
      out.write("\n");
      out.write(".cancelbtn {\n");
      out.write("    width: auto;\n");
      out.write("    padding: 10px 18px;\n");
      out.write("    background-color: #f44336;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".imgcontainer {\n");
      out.write("    text-align: center;\n");
      out.write("    margin: 24px 0 12px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("img.avatar {\n");
      out.write("    width: 40%;\n");
      out.write("    border-radius: 50%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("    padding: 16px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("span.psw {\n");
      out.write("    float: right;\n");
      out.write("    padding-top: 16px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("        .form-signin {\n");
      out.write("            max-width: 380px;\n");
      out.write("            padding: 15px 35px 45px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            background-color: #fff;\n");
      out.write("            border: 1px solid rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("        .form-signin-heading{\n");
      out.write("             margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("        input[type=\"text\"] {\n");
      out.write("	  background-color: #e5e5e5;\n");
      out.write("border: none;\n");
      out.write("border-radius: 3px;\n");
      out.write("-moz-border-radius: 3px;\n");
      out.write("-webkit-border-radius: 3px;\n");
      out.write("color: #5a5656;\n");
      out.write("font-family: 'Open Sans', Arial, Helvetica, sans-serif;\n");
      out.write("font-size: 14px;\n");
      out.write("height: 50px;\n");
      out.write("outline: none;\n");
      out.write("padding: 0px 10px;\n");
      out.write("width: 280px;\n");
      out.write("-webkit-appearance:none;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	input[type=\"password\"] {\n");
      out.write("	  background-color: #e5e5e5;\n");
      out.write("border: none;\n");
      out.write("border-radius: 3px;\n");
      out.write("-moz-border-radius: 3px;\n");
      out.write("-webkit-border-radius: 3px;\n");
      out.write("color: #5a5656;\n");
      out.write("font-family: 'Open Sans', Arial, Helvetica, sans-serif;\n");
      out.write("font-size: 14px;\n");
      out.write("height: 50px;\n");
      out.write("outline: none;\n");
      out.write("padding: 0px 10px;\n");
      out.write("width: 280px;\n");
      out.write("-webkit-appearance:none;\n");
      out.write("	}\n");
      out.write("     .wrapper {	\n");
      out.write("    margin-top: 80px;\n");
      out.write("    margin-bottom: 80px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("   	input[type=\"submit\"] {\n");
      out.write("background-color: #008dde;\n");
      out.write("border: none;\n");
      out.write("border-radius: 3px;\n");
      out.write("-moz-border-radius: 3px;\n");
      out.write("-webkit-border-radius: 3px;\n");
      out.write("color: #5a5656;\n");
      out.write("font-family: 'Open Sans', Arial, Helvetica, sans-serif;\n");
      out.write("font-size: 14px;\n");
      out.write("height: 50px;\n");
      out.write("outline: none;\n");
      out.write("padding: 0px 10px;\n");
      out.write("width: 280px;\n");
      out.write("-webkit-appearance:none;\n");
      out.write("}\n");
      out.write("        .form-group {\n");
      out.write("            width: 343px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css\" integrity=\"sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <title>Header</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        .head {\r\n");
      out.write("          margin: auto;\r\n");
      out.write("          width: 60%;\r\n");
      out.write("          padding: 10px;\r\n");
      out.write("          align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        a{\r\n");
      out.write("            margin-left: 80px;\r\n");
      out.write("            font-size: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"head\">\r\n");
      out.write("       <center><h1>RAMANA FERTILIZERS</h1></center>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <a href=\"home.jsp\"><i class=\"fa-solid fa-house\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("    <form action=\"reports.jsp\" id=\"form1\">\n");
      out.write("<div class=\"aspNetHidden\">\n");
      out.write("<input type=\"hidden\" name=\"__VIEWSTATE\" id=\"__VIEWSTATE\" value=\"ih3wb/CAwpezF0ZIm1JWCc6y5vhTvPFMzZZOnHUKeC6eJWZaqio5wTEFdAWTIghYdOXgJIIzxbOE6Huy53IxZxvb6uozpnV/8eKorbTnsI8=\" />\n");
      out.write("</div>\n");
      out.write("  \n");
      out.write("        <div>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            <table align=\"center\" style=\"font-size:25px\">\n");
      out.write("                  <tr style=\"color: #000000; font-size:30px; font-weight: bold; align-content:center font-size: 20px; font-family: Calibri;\">\n");
      out.write("                    <td>\n");
      out.write("                        GENERATE TRANSACTION REPORT\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"wrapper\">\n");
      out.write("               \n");
      out.write("            <div class=\"form-signin\"> \n");
      out.write("                      \n");
      out.write("      <h2 class=\"form-signin-heading\" style=\"font-family:'Times New Roman'\">Select the range</h2>\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("        <label>From :</label>\n");
      out.write("      <input name=\"from\" type=\"date\" id=\"username\" class=\"form-control\" name=\"username\"required=\"required\" autofocus=\"\" />\n");
      out.write("      </div>\n");
      out.write("              \n");
      out.write("  \n");
      out.write("\n");
      out.write("     \n");
      out.write("\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                      <label>To :</label>\n");
      out.write("      <input name=\"to\" type=\"date\" id=\"password\" class=\"form-control\" name=\"password\" required=\"required\" />      \n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                 <input type=\"submit\" name=\"login1\" value=\"SUBMIT\" id=\"login1\" />\n");
      out.write("     \n");
      out.write("                 \n");
      out.write("          \n");
      out.write("         \n");
      out.write("    </div>\n");
      out.write("               \n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>    \n");
      out.write("    </div>\n");
      out.write("        \n");
      out.write("         <div >\n");
      out.write("            <table style=\"width: 100%;\">\n");
      out.write("                    <tr>\n");
      out.write("\n");
      out.write("                        <td>\n");
      out.write("                            <img src=\"./Images/footerMenu.png\" width=\"100%\"  style=\"border-radius: 6px 6px 2px 2px\" />\n");
      out.write("                           \n");
      out.write("                        </td>\n");
      out.write("                        </tr>\n");
      out.write("              </table>\n");
      out.write("        </div>\n");
      out.write("    </form>\n");
      out.write("   \n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
